### ISSUE TITLE
Fabric 1.20.1

### ISSUE THREAD

**Issue by Snarke1** [willatendo/Roses#1]
I'm sorry if this comes off as annoying or if you maybe get this a lot but I logged into github for the first time just to ask this. Is there any possible way the Fabric version of your Roses mod could have a version for 1.20.1? I've had my eyes on this mod for a while and really want to use it in my pack since no other mod of this subject really delivers in the way this one does but most of the other mods I play with are still on 1.20.1 and its just a shame that the one good beta/unused content mod I've been able to find for Fabric isn't for the version I'm stuck on.

**Comment by willatendo** [comment]
I'm sorry, but I don't downport my mods. I understand it's annoying to have mods you want to use on separate versions (I've been there many times) but I don't enough time to run multiple versions. It's just not in my time budget. I'm sorry. I hope you can find a mod that does work! If you still don't, maybe the other mods will get updated. Thank you for supporting my mod, though!
